# Generated by Django 3.1.7 on 2021-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender_choice', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('age', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='BmiMeasurement',
        ),
    ]
