# Generated by Django 3.1.7 on 2021-04-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0002_auto_20210415_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='activity_choices',
            field=models.CharField(choices=[('no', 'Little or no exercise'), ('little', 'Exercise 1-3 days a Week'), ('moderate', 'Exercise, 3-5 days a week'), ('heavy', 'Heavy Exercise, 6-7 days a week'), ('veryheavy', 'Very heavy Exercise, twice per day')], default='NULL', max_length=150),
        ),
    ]
