# Generated by Django 3.1.7 on 2021-04-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietplan', '0003_userinfomodel_activity_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfomodel',
            old_name='weight',
            new_name='weight_in_kg',
        ),
    ]
